name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR
        run: mvn clean package

      - name: Build Docker Image
        run: docker build -t eks-automation .
      - name: Run Docker Container
        run: docker run -p 9000:9000 eks-automation



#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v2
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
#          aws-region: ap-south-1
#
#      - name: Login to ECR
#        run: |
#          aws ecr get-login-password --region ap-south-1 | \
#          docker login --username AWS --password-stdin <account-id>.dkr.ecr.ap-south-1.amazonaws.com
#
#      - name: Tag Image
#        run: |
#          docker tag eks-automation:latest <account-id>.dkr.ecr.ap-south-1.amazonaws.com/eks-automation:latest
#
#      - name: Push Image
#        run: |
#          docker push <account-id>.dkr.ecr.ap-south-1.amazonaws.com/eks-automation:latest